# Generated by Django 5.2.3 on 2025-07-18 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='defualt',
            new_name='default',
        ),
    ]
