# Generated by Django 5.2.3 on 2025-07-20 19:52

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_item_cats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(storage=storages.backends.s3.S3Storage(), upload_to='ecom/'),
        ),
    ]
