# Generated by Django 5.2.3 on 2025-07-18 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_address_options_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
