# Generated by Django 5.2.3 on 2025-07-19 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_payment_email_payment_ref_payment_verified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='item',
            name='cats',
            field=models.ManyToManyField(blank=True, null=True, to='core.cats'),
        ),
    ]
