# Generated by Django 5.2.3 on 2025-07-20 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_item_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='type_phone',
            field=models.CharField(blank=True, choices=[('BN', 'BRAND NEW'), ('U', 'LOCAL USED'), ('UK', 'UK USED')], max_length=19, null=True),
        ),
    ]
