# Generated by Django 5.2.3 on 2025-07-20 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_item_type_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='type_phone',
            field=models.CharField(choices=[('BN', 'BRAND NEW'), ('U', 'LOCAL USED'), ('UK', 'UK USED')], max_length=19),
        ),
    ]
